apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kura
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - imasjajca.lb.djnd.si
      secretName: kura-tls

  rules:
  - host: imasjajca.lb.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kura
            port:
              number: 80
