apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zicar
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zicar.djnd.si
        - zicar.danesjenovdan.si
      secretName: zicar-tls
  rules:
    - host: zicar.djnd.si
      http: &http_paths
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zicar
                port:
                  number: 80
    - host: zicar.danesjenovdan.si
      http: *http_paths
