apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kura
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: kura-en
    newName: rg.fr-par.scw.cloud/djnd/kura-en
    newTag: 'fe51f73970e45176463775fd54cc773223608778'
