apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zicar
resources:
  - deployment.yaml
  - service.yaml
  # - ingress.yaml
images:
  - name: zicar
    newName: rg.fr-par.scw.cloud/djnd/zicar
    newTag: "latest"
